### ISSUE TITLE
No License found

### ISSUE THREAD

**Issue by cmgriffing** [canopas/tailwind-animations#4]
First off, cool project.

Would you be willing to add a license file? Maybe I missed it, but I found no file or README entry. I also didn't see one in the package.json.

Even if proprietary, a clear license would be useful.

Thanks.

**Comment by cp-sumi-k** [comment]
Hello @cmgriffing, Thank you for your nice words.

Yes, the license is mandatory. Added in this [PR](https://github.com/canopas/tailwind-animations/pull/5)
